# This file tells Netlify how to build and deploy your site.

[functions]
  # This specifies the directory where your serverless functions are located.
  directory = "netlify/functions/"
  node_bundler = "esbuild"
